/**
 * Mockup data. The notes and the paths are copied from the docs kiln
 * (`docs/`) and the repository root; the `:::hunk` blocks in two notes are
 * synthetic agent edits. Nothing but the shell mockup page reads this module.
 */

/** Every note path of the docs kiln, without the `.md` extension. */
export const KILN_PATHS: readonly string[] = [
  "Agents/Coder",
  "Agents/General Assistant",
  "Agents/Index",
  "Agents/Kiln Specialist",
  "Agents/Researcher",
  "Agents/Reviewer",
  "Agents/Tool Capabilities",
  "AI Features",
  "Extending Crucible",
  "Guides/Basic Commands",
  "Guides/Getting Started",
  "Guides/GitHub Copilot Setup",
  "Guides/OpenRouter Setup",
  "Guides/Session Search",
  "Guides/Windows Setup",
  "Guides/Your First Kiln",
  "Guides/Z.AI Setup",
  "Help/Block References",
  "Help/Callouts",
  "Help/CLI/acp",
  "Help/CLI/chat",
  "Help/CLI/doctor",
  "Help/CLI/Index",
  "Help/CLI/kiln",
  "Help/CLI/lua",
  "Help/CLI/models",
  "Help/CLI/process",
  "Help/CLI/project",
  "Help/CLI/search",
  "Help/CLI/session",
  "Help/CLI/setup",
  "Help/CLI/skills",
  "Help/CLI/stats",
  "Help/Concepts/Agent Client Protocol",
  "Help/Concepts/Agent Skills",
  "Help/Concepts/Agents & Protocols",
  "Help/Concepts/Canvas",
  "Help/Concepts/Delegation",
  "Help/Concepts/Kilns",
  "Help/Concepts/Model Context Protocol",
  "Help/Concepts/Note Sync",
  "Help/Concepts/Oil",
  "Help/Concepts/Permission Precedence",
  "Help/Concepts/Plaintext First",
  "Help/Concepts/Precognition",
  "Help/Concepts/Reflection Pass",
  "Help/Concepts/Review Ledger",
  "Help/Concepts/Scripting Languages",
  "Help/Concepts/Semantic Search",
  "Help/Concepts/Session Compaction",
  "Help/Concepts/Session Replay",
  "Help/Concepts/The Knowledge Graph",
  "Help/Concepts/Trust and Classification",
  "Help/Config/acp",
  "Help/Config/agents",
  "Help/Config/embedding",
  "Help/Config/llm",
  "Help/Config/mcp",
  "Help/Config/permissions",
  "Help/Config/storage",
  "Help/Configuration",
  "Help/Config/web",
  "Help/Config/Workspaces",
  "Help/Core/Sessions",
  "Help/Delegation Patterns",
  "Help/Diagrams and Math",
  "Help/Extending/Agent Cards",
  "Help/Extending/Container Isolation",
  "Help/Extending/Creating Plugins",
  "Help/Extending/Custom Handlers",
  "Help/Extending/Custom Tools",
  "Help/Extending/Discord",
  "Help/Extending/Event Hooks",
  "Help/Extending/HTTP Module",
  "Help/Extending/Internal Agent",
  "Help/Extending/MCP Gateway",
  "Help/Extending/Script Agent Queries",
  "Help/Extending/Scripted UI",
  "Help/Extending/Web Theme Tokens",
  "Help/Extending/Workflow Authoring",
  "Help/Extending/Worktree Sessions",
  "Help/Footnotes",
  "Help/Frontmatter",
  "Help/Lua/Configuration",
  "Help/Lua/Language Basics",
  "Help/Lua/Testing Plugins",
  "Help/Operations/Discord Bot Runbook",
  "Help/Plugins/Lua Runtime API",
  "Help/Plugins/Oil Lua API",
  "Help/Plugins/Vendoring Lua Dependencies",
  "Help/Query/Index",
  "Help/Query/Query System",
  "Help/Rules Files",
  "Help/Tags",
  "Help/Task Management",
  "Help/TOON Format",
  "Help/TUI/Commands",
  "Help/TUI/Index",
  "Help/TUI/Keybindings",
  "Help/TUI/Modes",
  "Help/TUI/Shell Execution",
  "Help/Wikilinks",
  "Help/Workflows/Index",
  "Help/Workflows/Workflow Syntax",
  "Index",
  "Meta/Architecture/Actual",
  "Meta/Architecture/Config Boot",
  "Meta/Architecture/Consolidation Plan",
  "Meta/Architecture/Expected",
  "Meta/Architecture/Gaps",
  "Meta/Architecture/Index",
  "Meta/Architecture/Mobile Shell",
  "Meta/Architecture/State Stores",
  "Meta/Architecture/Web Windowing",
  "Meta/CONTEXT",
  "Meta/Plugin Conventions",
  "Meta/Plugin User Stories",
  "Meta/Product",
  "Meta/Product Decision Log",
  "Meta/TUI/Component Architecture",
  "Meta/TUI/E2E Testing",
  "Meta/TUI Style Guide",
  "Meta/TUI User Stories",
  "Meta/Web User Stories",
  "Organization Styles/Choosing Your Structure",
  "Organization Styles/Index",
  "Organization Styles/Johnny Decimal",
  "Organization Styles/PARA",
  "Organization Styles/Zettelkasten",
  "Search & Discovery"
];

/**
 * Files of the docs kiln that are not notes, with their extensions. The real
 * docs kiln has none; these show how the tree labels a canvas, an image and
 * a data file.
 */
export const KILN_FILES: readonly string[] = [
  "Help/Concepts/Knowledge Map.canvas",
  "Help/Concepts/precognition-flow.png",
  "Help/Concepts/session-states.json",
];

/**
 * The files by the time of their last change, the newest first, for the
 * tree's "Modified" order. A file that is not in this list is older than
 * all of them. The real app reads `mtime` from `useListDir`.
 */
export const RECENT_FILES: readonly string[] = [
  "Help/Concepts/Precognition.md",
  "Help/Concepts/Knowledge Map.canvas",
  "Help/Concepts/Semantic Search.md",
  "Help/Concepts/Review Ledger.md",
  "Help/Concepts/Kilns.md",
  "Help/Concepts/precognition-flow.png",
  "Help/Concepts/Session Compaction.md",
];

/** The top level of the crucible project root. A trailing `/` marks a folder. */
export const PROJECT_PATHS: readonly string[] = [
  "AGENTS.md",
  "assets/",
  "Cargo.lock",
  "Cargo.toml",
  "CHANGELOG.md",
  "CODE_OF_CONDUCT.md",
  "CONTRIBUTING.md",
  "crates/",
  "deny.toml",
  "docs/",
  "docs-site/",
  "examples/",
  "justfile",
  "LICENSE-APACHE",
  "LICENSE-MIT",
  "README.md",
  "runtime/",
  "scripts/",
  "SECURITY.md",
  "tests/",
  "THIRD-PARTY-NOTICES.md",
  "vendor/"
];

/** Note text by path. Only these notes carry their text in the mockup. */
export const NOTE_TEXT: Record<string, string> = {
  "Help/Concepts/Precognition": "---\ntitle: Precognition\ndescription: How Crucible automatically surfaces relevant notes during conversation\nstatus: implemented\ntags: [precognition, rag, context, embeddings, knowledge-graph]\n---\n# Precognition\n\nPrecognition is Crucible's way of giving your agent a memory. Before your opening message reaches the LLM, Crucible searches your knowledge base for relevant notes and quietly injects them into the conversation. Your agent sees what you've written before, without you lifting a finger.\n\n:::hunk h1\n-Think of it as your notes whispering context to the AI right when it needs it.\n+It runs once, on the first message of a session, and it is on by default. To turn it off for one session, run `:set noprecognition` before that message.\n:::\n\n## Why It Matters\n\nWithout Precognition, your agent starts every conversation from scratch. It doesn't know what you wrote last week, what decisions you've made, or what your project looks like. You'd have to copy-paste context manually or hope the AI guesses right.\n\nWith Precognition turned on, your [[The Knowledge Graph|knowledge graph]] becomes the agent's long-term memory. Notes you wrote months ago can surface in today's conversation if they're relevant. The more you write, the smarter your agent gets.\n\n## How It Works\n\nThe process is invisible. Here's what happens on the first message of a session:\n\n1. **You type a message** and hit enter\n2. **Crucible searches** your vault using [[Semantic Search|semantic search]], finding notes whose meaning matches your message\n3. **Top results get injected** into the prompt as additional context, before the LLM ever sees it\n4. **The agent responds** with awareness of your existing notes, links, and ideas\n\nAll of this happens in the background. You see a brief notification showing how many notes were found, then the response arrives as usual.\n\n## What Gets Searched\n\nPrecognition retrieves at the **block level**. During indexing, each block of a note is embedded with its own vector and its byte span, so retrieval matches your message against passages and injects the passage that matched.\n\nEvery kiln the session is attached to is searched. The set is flat — no member is privileged by having been attached first — so results are merged and ranked together, and a kiln whose data classification exceeds the session provider's trust level is skipped entirely (see [[Trust and Classification]]).\n\n## Configuration\n\nPrecognition is **on by default**. You can control it from within a chat session using `:set` commands.\n\n### Toggle On/Off\n\n```\n:set precognition        # turn on\n:set noprecognition      # turn off\n:set precognition!       # toggle\n```\n\n### Number of Results\n\nHow many notes get injected per message is a config key, `chat.precognition_results` (default 5). It is one value per install rather than per session:\n\n```lua\ncru.config.set { chat = { precognition_results = 3 } }\n```\n\nMore results means more context for the agent, but also uses more of the context window. Start with the default and adjust based on how your conversations feel.\n\n### Checking Current Settings\n\n```\n:settings\n```\n\nThis shows all current values, including `precognition`. The result count is a config key — `:config` shows it with the rest of `chat`.\n\n### Customizing with Lua\n\nPlugins can reshape Precognition through two event seams:\n\n- `precognition_select` — runs after retrieval, before injection. A handler sees the retrieved notes and chooses which to keep.\n- `precognition_format` — controls how the selected notes are rendered into the injected context block.\n\nRegister handlers with `cru.on(\"precognition_select\", ...)`. See [[Help/Extending/Event Hooks]] for handler signatures and semantics.\n\n## When It Activates\n\nPrecognition runs on the **first user message of a session** — not on every turn. Re-injecting on each turn bloats the context, costs prompt-cache hits, and mostly surfaces notes the opening injection already covered.\n\nThree things stop it running even on a first message:\n\n- **Turned off**: `:set noprecognition`\n- **Search commands**: Messages starting with `/search` skip enrichment\n- **No knowledge base**: If you're running in lightweight mode without a processed vault, there's nothing to search\n\n## Requirements\n\n1. **A processed vault**: Run `cru process` on your notes at least once so embeddings exist\n2. **An embedding provider**: Crucible needs a way to generate embeddings (Ollama, FastEmbed, or OpenAI)\n3. **Notes worth finding**: The more you write and link, the better Precognition gets\n\n## Tips for Better Results\n\n**Write notes you'd want to find later.** Clear titles, descriptive paragraphs, and specific details all help semantic search find the right content.\n\n**Use wikilinks.** Links between notes strengthen the [[The Knowledge Graph|knowledge graph]]. When Precognition finds one note, related linked notes become easier to surface too.\n\n**Keep notes focused.** A note about one topic is more useful than a note about everything.\n",
  "Help/Concepts/Review Ledger": "---\ntitle: Review Ledger\ndescription: Per-session attributed changes, the composed diff, the review queue, and the gate that holds unreviewed writes\nstatus: implemented\ntags: [review, sessions, attribution, web, agents]\n---\n# Review Ledger\n\nThe review ledger answers two questions about an agent session: *what changed*, and *which tool call did it*. Every writing tool call is bracketed by git tree snapshots of the session's roots, and the difference between the session's starting tree and the worktree now — the **composed diff** — becomes a queue of hunks you accept or reject. In `ask` mode, a **review gate** holds any further write to a file until its unreviewed hunks are dealt with.\n\nThe evidence is the filesystem, not the agent's claims: changes are keyed on git tree SHAs rather than on what a call reported, so attribution works the same for the internal agent and for external [[Agent Client Protocol|ACP]] agents.\n\n## What gets tracked\n\nWhen a session's first message is sent, the daemon opens a ledger over the session's workspace and every [[Kilns|kiln]] it is attached to. A root outside a git repository — a kiln outside git is the expected shape — is snapshotted into a plain store under the daemon data root.\n\nTwo kinds of change deliberately get no attribution:\n\n- **Your own edits.** Anything changed outside a bracket surfaces as an *external* hunk — listed so the diff stays honest, but never blockable and never rejectable.\n- **Binary files.** Non-UTF-8 files have no line hunks and are skipped.\n\n## The review queue\n\nEach hunk is `unreviewed`, `accepted`, or `rejected`. Absent a recorded decision, a hunk is unreviewed — decisions never transfer to lines the reviewer did not see.\n\n- **Accept** records the decision, silently.\n- **Reject** is one operation: the daemon reverts the hunk on disk immediately, records the rejection, and injects a user-role note into the session's conversation naming the file and lines.\n- **Undo** takes a reject back. Every reject, single or bulk, pushes one batch onto a per-session stack that the journal records, so the stack is multi-level and survives a daemon restart.\n\nA listing has a **scope**: `session` lists every hunk since `session_base`; `turn` lists only the hunks a tool call of the current turn touched.\n",
  "Help/Concepts/Semantic Search": "---\ntitle: Semantic Search\ndescription: How Crucible finds content based on meaning, not just keywords\nstatus: implemented\ntags: [concept, search, ai]\n---\n# Semantic Search\n\nSemantic search finds content based on **meaning**, not just matching words. When you search for \"productivity techniques\", it also finds notes about \"getting things done\", \"focus methods\", and \"time management\" - even if they don't contain your exact words.\n\n## How It Works\n\n1. **Indexing**: When you run `cru process`, Crucible reads each note and creates an \"embedding\" - a numerical representation of its meaning\n2. **Searching**: When you search, your query is also converted to an embedding\n3. **Matching**: Crucible finds notes whose embeddings are closest to your query's embedding\n\nCrucible embeds each block of a note and stores it in `note_blocks`, one row per block with its byte span. `cru search`, the `search_vectors` RPC, the search tool and **precognition** all retrieve through that table, so a hit names the passage that matched rather than the file it sat in.\n\n## Using Semantic Search\n\n```bash\n# Find content similar to your query\ncru search \"how do I stay focused while working?\" --type semantic\n\n# Limit results\ncru search \"project planning\" --type semantic --limit 5\n```\n\nWithout `--type`, `cru search` combines semantic and text results.\n",
  "Index": "---\ntitle: Index\ndescription: The dev-kiln - documentation and working example for Crucible\nstatus: implemented\ntags: [index, guide, welcome]\n---\n# Welcome to Crucible\n\n**Crucible** is a knowledge-grounded agent runtime. Agents that draw from a knowledge graph make better decisions — memory and knowledge are too fundamental to be an afterthought. Your notes, conversations, and wikilinks form that graph. Everything beyond the knowledge core is extensible via Lua scripting and plugins.\n\n## How It Works\n\n### Knowledge enters\n\nNotes, wikilinks, tags, and sessions-as-notes are how knowledge gets into the system. Write markdown, link ideas with `[[wikilinks]]`, and every conversation you have becomes a searchable, linkable note in your [[Help/Concepts/Kilns|kiln]].\n\n- **[[Help/Concepts/Kilns]]** — What makes a kiln\n- **[[Help/Concepts/The Knowledge Graph]]** — How wikilinks connect ideas\n- **[[Help/Concepts/Plaintext First]]** — Why markdown matters\n\n### Knowledge activates\n\n[[Help/Concepts/Precognition|Precognition]] is the core expression of this philosophy: before every message reaches the LLM, Crucible searches your knowledge graph and silently injects relevant context. Your notes whisper to the agent. The more you write and link, the smarter your agents get.\n\n- **[[Help/Concepts/Precognition]]** — Auto-RAG from your knowledge graph\n- **[[Help/Concepts/Semantic Search]]** — Finding by meaning, not just keywords\n- **[[Help/Concepts/Agents & Protocols]]** — MCP, ACP, and how agents connect\n\n## Getting Started\n\n```bash\n# Start an AI chat session\ncru chat\n\n# Process your notes for search\ncru process\n```\n\nNew to Crucible? Start here:\n\n1. **[[Guides/Getting Started]]** — Your first steps with Crucible\n2. **[[Guides/Your First Kiln]]** — Create and configure a new kiln\n3. **[[Help/CLI/chat]]** — Start chatting with AI\n4. **[[Help/Wikilinks]]** — The link syntax that powers everything\n",
  "Help/Concepts/Kilns": "---\ntitle: Kilns\ndescription: What makes a kiln\nstatus: implemented\ntags: [concept, kiln]\n---\n# Kilns\n\nA **kiln** is a directory of markdown files that Crucible treats as a connected knowledge base. Think of it like an Obsidian vault — a living collection of notes that grows and evolves over time. As you write, link, and converse, the knowledge graph deepens naturally. That growing graph is what gives your agents their memory.\n\nWhen you start using Crucible in a folder, it becomes a kiln — a living knowledge base that grows with you. As you add notes and conversations, [[Precognition]] draws on the whole graph to give your agents context.\n\n:::hunk h3\n+A session attaches kilns as a flat set. No kiln is privileged by the order in which it was attached, and the session's transcript lives under the daemon data root, not in a kiln.\n:::\n\n## Crucible's own documentation, as a kiln\n\n`Help/` and `Guides/` ship inside the `cru` binary and extract on first daemon start. They are offered as a kiln named `crucible-docs`, **lazy** — never opened, indexed or searched until you ask for it.\n",
  "Help/Extending/Web Theme Tokens": "---\ntitle: Web Theme Tokens\ndescription: Restyle the web UI from a plugin with one stylesheet of CSS custom properties\nstatus: partial\ntags: [extending, web, theme, css, plugins]\n---\n# Web Theme Tokens\n\nThe web UI reads every colour, radius, row height and type size from a CSS custom property. The property names start with `--cru-`. They are public. A plugin sets them in one stylesheet, and the whole app follows.\n\nThe contract has three promises:\n\n1. A plugin sets a value. It never names a component class.\n2. A plugin writes no `!important`. The cascade gives the plugin the win.\n3. A name in the table below does not change. A new name can appear.\n\n## How an override wins\n\nThe app declares its defaults inside a CSS cascade layer named `cru-theme`. An unlayered rule beats a layered rule at any specificity. A plugin stylesheet declares no layer, so its rules are unlayered.\n\n```css\n:root                      { --cru-color-primary: #3a7fe0; }  /* both themes */\n:root[data-theme='light']  { --cru-color-primary: #1f4a91; }  /* light only  */\n```\n\nTo try it in this mockup, open Settings at the bottom of the left rail and choose a plugin stylesheet.\n",
  "Help/Concepts/The Knowledge Graph": "---\ntitle: The Knowledge Graph\ndescription: How wikilinks create an interconnected web of knowledge\nstatus: implemented\ntags:\n  - concept\n  - wikilinks\n  - navigation\n---\n\n# The Knowledge Graph\n\nWhen you link notes together with `[[wikilinks]]`, you're building a **knowledge graph** - a web of connected ideas that grows more valuable as you add to it.\n\n## Links Create Structure\n\nEvery `[[link]]` you write creates a connection:\n\n```markdown\n# Machine Learning\n\nMachine learning is a subset of [[Artificial Intelligence]] that\nfocuses on learning from [[Data]] rather than explicit programming.\n\nKey concepts:\n- [[Neural Networks]]\n- [[Training Data]]\n- [[Overfitting]]\n```\n\nThese links define relationships. Over time, clusters of related notes emerge naturally.\n\n## Why Links Matter\n\nLinks do three things:\n\n1. **Navigation** - Move between related ideas quickly\n2. **Discovery** - Find notes you forgot about through connections\n3. **Context** - See how ideas relate to each other\n\n## Backlinks\n\nEvery link goes both ways. When Note A links to Note B, Note B knows about it. This creates \"backlinks\" - a list of everything that references a note.\n\nYou didn't have to create those connections manually. They emerge from your natural writing.\n\n## Links vs Folders\n\n| Folders | Links |\n|---------|-------|\n| One location per note | Many connections per note |\n| Hierarchy | Network |\n| Exclusive categories | Overlapping relationships |\n| Decided upfront | Emerges naturally |\n\nYou can use both. Folders organize files; links organize ideas.\n\n## Building Your Graph\n\n**Start small:**\n- Link when you think of a connection\n- Don't force links that don't feel natural\n- Review notes occasionally and add links you missed\n\n**Let structure emerge:**\n- Clusters of densely-linked notes appear over time\n- Hub notes (like [[Index]]) help navigation\n- You'll notice patterns in how you think\n\n## See Also\n\n- [[Help/Wikilinks]] - Link syntax reference\n- [[Help/Block References]] - Linking to specific paragraphs\n- [[Organization Styles/Zettelkasten]] - A link-centric approach\n- [[Search & Discovery]] - Finding content in your graph\n",
};
