mod auth;
mod chat;
mod config;
mod health;
mod helpers;
mod kiln;
mod layout;
mod mcp;
mod plugin;
mod project;
mod search;
mod session;
mod session_commands;
mod session_config;
mod shell;
mod skills;
mod terminal;
mod webhook;

pub use auth::auth_routes;
pub use chat::chat_routes;
pub use config::config_routes;
pub use health::health_routes;
pub use kiln::kiln_routes;
pub use layout::layout_routes;
pub use mcp::mcp_routes;
pub use plugin::plugin_routes;
pub use project::project_routes;
pub use search::search_routes;
pub use session::session_routes;
pub use shell::shell_routes;
pub use terminal::terminal_routes;
pub use skills::skills_routes;
pub use webhook::webhook_routes;
