/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/chat/events/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * The session's live event stream.
         * @description The body schema describes one SSE `data:` payload, not the whole stream:
         *     OpenAPI has no way to say "many of these, one per line".
         */
        get: operations["event_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live filesystem-change stream for the file-tree explorer.
         * @description The body schema describes one SSE `data:` payload, not the whole stream.
         */
        get: operations["fs_event_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * All chat models across providers, no session required (draft-state picker).
         * @description Takes no `kiln` parameter, for the reason `list_providers` does not: it
         *     used to accept a raw `PathBuf` that reached the daemon's classification
         *     resolver unfloored, and no caller ever sent one.
         */
        get: operations["list_all_models"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * `GET /api/plugins/events` — a push when a plugin's published data changes.
         * @description The counterpart to `GET /api/plugins/publications`: that answers "what is
         *     true now", this says "read it again". A panel drawing a plugin's own state
         *     would otherwise poll on a timer and still show a stale value between ticks.
         *
         *     Same shape as the file-tree stream in `routes/fs.rs`, including the
         *     load-bearing ordering: subscribe the LOCAL broker channel before telling the
         *     daemon to forward, because `EventBroker::dispatch` drops events for a
         *     session id with no local subscriber and the window between the two calls
         *     would lose the first event.
         */
        get: operations["publication_event_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/shell/exec": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run one command and stream its output.
         * @description The router nests under `/api/shell`, so the document reads this path as
         *     `/api/shell/exec`. The body schema describes one SSE `data:` payload, not
         *     the whole stream.
         */
        post: operations["shell_exec"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/surfaces/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live stream of surface changes.
         * @description The body schema describes one SSE `data:` payload, not the whole stream.
         */
        get: operations["surface_event_stream"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description The browser's view of a session event, streamed by `GET
         *     /api/chat/events/{session_id}`.
         *
         *     `ToSchema` publishes the 22 tag values to the OpenAPI document, so the
         *     browser reads the union from the enum instead of repeating it.
         */
        ChatEvent: {
            content: string;
            /** @enum {string} */
            type: "token";
        } | {
            arguments?: unknown;
            id: string;
            title: string;
            /** @enum {string} */
            type: "tool_call";
        } | {
            id: string;
            result?: string | null;
            /**
             * @description True if this tool requested an agent-turn early-stop
             *     (daemon's conjunctive batch-terminate check fired). UI renders
             *     a "Terminated" badge on the tool card.
             */
            terminate?: boolean;
            /** @enum {string} */
            type: "tool_result";
        } | {
            delta: string;
            id: string;
            /** @enum {string} */
            type: "tool_result_delta";
        } | {
            id: string;
            /** @enum {string} */
            type: "tool_result_complete";
        } | {
            error: string;
            id: string;
            /** @enum {string} */
            type: "tool_result_error";
        } | {
            content: string;
            /** @enum {string} */
            type: "thinking";
        } | {
            content: string;
            /** Format: int64 */
            index: number;
            message_id: string;
            /** @enum {string} */
            type: "segment_complete";
        } | {
            /** Format: int64 */
            cache_creation_tokens?: number | null;
            /** Format: int64 */
            cache_read_tokens?: number | null;
            /** Format: int64 */
            completion_tokens?: number | null;
            content: string;
            id: string;
            /** Format: int64 */
            prompt_tokens?: number | null;
            /**
             * @description The note the browser draws under a reply the provider cut off, or
             *     absent when the reason needs none — which is every normal turn.
             *
             *     **The daemon words it, not the page.** `StopReason::user_notice`
             *     is the only wording; the browser held a second one in TypeScript
             *     and the two drifted. One `Option<String>` once per turn is cheaper
             *     than a wording nothing compares, and `AGENTS.md` puts the decision
             *     in the daemon for exactly this reason: a web front end must not
             *     duplicate it.
             */
            stop_notice?: string | null;
            /**
             * @description Why the turn ended (`end_turn`, `max_tokens`, `refusal`, …). The
             *     browser reads it to style the turn. Absent when the daemon
             *     reported none.
             *
             *     It is a `String` in the document because `StopReason` lives in
             *     `crucible-core`, which takes no utoipa dependency. The values are
             *     `StopReason::ALL`, serialised snake_case.
             */
            stop_reason?: string | null;
            /** Format: int64 */
            total_tokens?: number | null;
            /** @enum {string} */
            type: "message_complete";
        } | {
            code: string;
            message: string;
            /** @enum {string} */
            type: "error";
        } | (unknown & {
            id: string;
        } & {
            /** @enum {string} */
            type: "interaction_requested";
        }) | {
            id: string;
            prompt: string;
            /** @enum {string} */
            type: "subagent_spawned";
        } | {
            id: string;
            summary: string;
            /** @enum {string} */
            type: "subagent_completed";
        } | {
            error: string;
            id: string;
            /** @enum {string} */
            type: "subagent_failed";
        } | {
            id: string;
            prompt: string;
            target_agent?: string | null;
            /** @enum {string} */
            type: "delegation_spawned";
        } | {
            id: string;
            summary: string;
            /** @enum {string} */
            type: "delegation_completed";
        } | {
            error: string;
            id: string;
            /** @enum {string} */
            type: "delegation_failed";
        } | {
            /** Format: int64 */
            total: number;
            /** @enum {string} */
            type: "context_usage";
            /** Format: int64 */
            used: number;
        } | {
            notes?: components["schemas"]["PrecognitionNote"][];
            notes_count: number;
            /** @enum {string} */
            type: "precognition_result";
        } | {
            mode: string;
            /** @enum {string} */
            type: "mode_changed";
        } | {
            title: string;
            /** @enum {string} */
            type: "title_changed";
        } | {
            data: unknown;
            event: string;
            /** @enum {string} */
            type: "session_event";
        };
        /**
         * @description A filesystem change delivered to the browser.
         *
         *     Serializes with an internal `type` tag whose values are `changed` /
         *     `deleted` / `moved` (e.g. `{"type":"changed","path":"/abs","kind":"modified"}`).
         *     The SSE `event:` name is separate — see [`FsEvent::event_name`].
         */
        FsEvent: {
            kind: string;
            path: string;
            /** @enum {string} */
            type: "changed";
        } | {
            path: string;
            /** @enum {string} */
            type: "deleted";
        } | {
            from: string;
            to: string;
            /** @enum {string} */
            type: "moved";
        };
        /**
         * @description Response for model listings — the session-scoped `list_models` and the
         *     session-less `list_all_models` return the same `{ models: [...] }` shape.
         */
        ModelsResponse: {
            models: string[];
        };
        PrecognitionNote: {
            name: string;
            /** Format: double */
            relevance?: number;
        };
        /**
         * @description A plugin's published data changed, delivered to the browser.
         *
         *     Carries who published and under which key, never the value — the same
         *     contract the daemon event has, and for the same reason: a publication is
         *     opaque JSON of the plugin's own choosing. The browser refetches through
         *     `GET /api/plugins/publications`.
         *
         *     Projected through a named type rather than passed through as raw `data`,
         *     which is the treatment `SurfaceChangedEvent` already gets: a field the
         *     daemon renames then breaks the browser with nothing on this side to notice.
         */
        PublicationChangedEvent: {
            key: string;
            plugin: string;
        };
        ShellEvent: {
            data: string;
            /** @enum {string} */
            type: "stdout";
        } | {
            data: string;
            /** @enum {string} */
            type: "stderr";
        } | {
            /** Format: int32 */
            code: number;
            /** @enum {string} */
            type: "exit";
        } | {
            message: string;
            /** @enum {string} */
            type: "error";
        };
        ShellExecRequest: {
            command: string;
            /** Format: int64 */
            timeout_secs?: number | null;
        };
        /**
         * @description A surface changed, delivered to the browser.
         *
         *     Carries the identity and the new version, never the rows — the same contract
         *     the daemon event has, and for the same reason: a surface is unbounded where an
         *     event is not, and two clients want it at different moments. The browser
         *     refetches through `GET /api/surfaces`.
         */
        SurfaceChangedEvent: {
            name: string;
            plugin: string;
            session?: string | null;
            /** Format: int64 */
            version: number;
            /**
             * @description The surface is gone, so the browser drops it instead of refetching.
             *
             *     Passed through rather than re-derived. The daemon knew this when it
             *     dropped the entry, and a browser that had to ask `GET /api/surfaces`
             *     to find out would pay a round trip for a fact the event already held.
             */
            withdrawn?: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaChatEvent = components['schemas']['ChatEvent'];
export type SchemaFsEvent = components['schemas']['FsEvent'];
export type SchemaModelsResponse = components['schemas']['ModelsResponse'];
export type SchemaPrecognitionNote = components['schemas']['PrecognitionNote'];
export type SchemaPublicationChangedEvent = components['schemas']['PublicationChangedEvent'];
export type SchemaShellEvent = components['schemas']['ShellEvent'];
export type SchemaShellExecRequest = components['schemas']['ShellExecRequest'];
export type SchemaSurfaceChangedEvent = components['schemas']['SurfaceChangedEvent'];
export type $defs = Record<string, never>;
export interface operations {
    event_stream: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The session to stream */
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ChatEvent"];
                };
            };
        };
    };
    fs_event_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["FsEvent"];
                };
            };
        };
    };
    list_all_models: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelsResponse"];
                };
            };
        };
    };
    publication_event_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["PublicationChangedEvent"];
                };
            };
        };
    };
    shell_exec: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShellExecRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ShellEvent"];
                };
            };
        };
    };
    surface_event_stream: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SurfaceChangedEvent"];
                };
            };
        };
    };
}
